### PR TITLE
Add footer api contract

### PR DESCRIPTION
**Pull request by goelsonali**
Footer page 

Related to issue - #9

Screenshot

image

image

### CODE REVIEW

**Comment by goelsonali** [comment]
@dricazenck - Mistakenly my old PR got closed, I clicked wrong button.. so created this new PR with the latest changes merged from main branch. And will create separate PR for parameter improvements

**Comment by dricazenck** [comment]
> my old PR got closed, I clicked wrong button.. so created this new PR with the latest changes merged from main branch. And will create separate PR for parameter improvements

But we can open I think is not a problem.

**Review by dricazenck — APPROVED** [review]

**Comment by stepsen89** [comment]
What values are you referring to with title, subtitle and description and link? 

image

**Comment by goelsonali** [comment]
> What values are you referring to with title, subtitle and description and link?
> 
@stepsen89  - Adriana has helped highlighting this, can you check if this looks fine to you.
image

**Pull request merged**
